### ISSUE TITLE
数字化生活

### ISSUE THREAD

**Issue by xiang578** [xiang578/xiang578.github.io#1]
数字世界真的很精彩，但我感觉自己不是他的主宰，而是奴隶。

目标：心静如水

**Comment by xiang578** [comment]
## Misc:
* [ ] 每日日记规范
* [x] Github 星标项目整理
* [ ] 百度云文件整理
* [ ] Mac 文件整理
* [ ] 坚果云文件整理
* [x] 浏览器书签整理
* [x] 自动化程序清单 @done (2018-09-20)
* [x] Mweb 整理 @done (2018-09-20)


## 纯文本任务管理 #1[x]* [ ] Alfred 与 TaskPaper 相[x]件
* [x] TaskPaper 教程阅读整理 @done (2018-09-20)
* [ ] PlainTasks 用法
* [x] TodoFlow @done (2018-09-20)
* [ ] TodoReview

## Peak Writing:
* [ ] 007 文章提前准备方法
* [ ] 灵感
* [ ] 资料整理
* [ ] 排版
* [ ] 多平台发布流程

## Todoist #4
* [-] Todoist 保存 chrome 链接的方法 @cancelled (2018-09-20)
* [-] 日常使用心得 @cancelled (2018-09-20)

## Toggl #5
* [ ] 分类调整
* [x] 阅读相关的文章 @done (18-04-10 13:45)
       - 文章不会有什么新意的，软件的本质还是你怎么使用它
* [x] python api 接口生成日常报告 @done (2018-09-20)
       - <参考:https://github.com/linesh-simplicity/linesh-simplicity.github.io/issues/113>

 ## Anki #6
* [ ] 整理笔记原则
* [ ] 日常背诵方式
* [ ] 读书笔记整理

 ## Mac #7
* [ ] 软件清单 @aritcle
* [ ] 系统备份的方法

## iPhone #8
* [ ] 软件清单 @aritcle
* [ ] 备份以及恢复的方法

## Github 
* [ ] Issues 使用规范
* [ ] 相关用到的软件

## MoneyWiz: 
* [x] 教程 @done (2018-09-20)
* [ ] 使用心得

**Comment by xiang578** [comment]
测试项目管理

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
