### ISSUE TITLE
时间管理系统

### ISSUE THREAD

**Issue by xiang578** [xiang578/xiang578.github.io#4]
### ⓹ 明确「下一步行动」

- [x] 阅读参考资料 [如何使用 Toggl：《活在当下：在时间的陪伴下向着目标持续前进着》](https://github.com/JimmyLv/jimmylv.github.io/issues/103)
- [x] [如何对时间进行分类？](https://github.com/JimmyLv/jimmylv.github.io/issues/96)
- [x] [记录时间这件小事儿](https://github.com/JimmyLv/jimmylv.github.io/issues/85)
- [ ] 阅读《奇特的一生》
- [ ] #20 时间日志

**Comment by xiang578** [comment]
重新划分项目，取消这个项目
